version: '2'

services:
  dashboard:
    build: cabify-dashboard/
    environment:
      - ES_ENDPOINT_EXTERNAL=${ES_ENDPOINT_EXTERNAL}
      - NODE_PATH=${NODE_PATH}
      - APP_NAME=${DASHBOARD_NAME}
    volumes:
     - ./cabify-dashboard/:/usr/src/app/
    networks:
      - dashboard-network
    ports:
     - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - dashboard-network
    ports:
      - 9200:9200

  senpy:
    build: senpy/
    environment:
      - BABELFY_API_KEY=${BABELFY_API_KEY}
    networks:
      - dashboard-network
    ports: 
      - "5000:5000"

  luigid:
    image: axiom/docker-luigi:latest-alpine
    networks:
      - dashboard-network
    ports:
      - "8082:8082"

  orchestrator:
    image: orchestrator-cabify
    build: orchestrator/
    depends_on:
      - "elasticsearch"
      - "senpy"
      - "luigid"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - ES_NETWORK_LOCATION=${ES_NETWORK_LOCATION}
      - SENPY_NETWORK_LOCATION=${SENPY_NETWORK_LOCATION}
    tty: true
    volumes:
      - observatorydata1:/usr/src/app/data/
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dashboard-network

volumes:
  esdata1:
    driver: local

  observatorydata1:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_DIRECTORY_PATH}
      o: bind

networks:
  dashboard-network:
    driver: bridge